config/routes.rb
Rails.application.routes.draw do
  #resources :organizacion
  get 'admin/index'
  get 'sesion/crear'
  get 'sesion/eliminarSesion' => 'sesion#eliminarSesion', as: "cerrarSesion"
  get 'sesion', to: 'sesion#inicio'
  post 'sesion', to: 'sesion#crear'
  #routes Acceso 
  get 'acceso', to: 'acceso#index'
  post 'acceso', to: 'acceso#verificacion'

  #routes usuario
  get 'usuario', to: 'usuario#index'
  get 'usuario/nuevo', to: 'usuario#nuevo'
  post 'usuario', to: 'usuario#crearUsuario'
  get 'usuario/:id' => 'usuario#editar', as: 'usuario_editar'
  get 'usuario/:id' => 'usuario#mostrar', as: 'usuario_mostrar'
  patch 'usuario/:id' => 'usuario#actualizar'
  put 'usuario/:id' => 'usuario#actualizar'

  delete "usuario/:id" => "usuario#eliminar", as: "usuario_eliminar"

  #routes verificacion
  get 'verificacion', to: 'verificacion#index'
  post 'verificacion', to: 'verificacion#buscando'
  get 'verificacion/credencial', to: 'verificacion#credencial'

 # resources :organizacion, :organizacion_path => { :update  => 'actualizar', :create => 'registrarOrganizacion'}
  #resources  :organizacions, controller: 'organizacion'
  #resolve("organizacions") { [:organizacion]  }
  #get 'organizacions', controlller: 'organizacion'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get  "organizacion" => "organizacion#index"
  get "organizacion/registrar" =>  "organizacion#registrar", as: :organizacion_nueva
  post "organizacion"  => "organizacion#registrarOrganizacion"
  patch "organizacion/:id/" => "organizacion#actualizar"
  put "organizacion/:id/" => "organizacion#update"
  get 'organzacion/:id' => 'organizacion#mostrar', as: :organizacion_mostrar
  get "organizacion/:id/", to: "organizacion#editar", as: :organizacion_editar

  delete "organizacion/:id" => "organizacion#eliminar", as: "organizacion_eliminar"
  #resources  :organizacion, only: [:update ]

  #This routes Persona controller and model
  get "persona", to: "persona#index"
  post "persona", to: "persona#registrarPersona"
  post "persona/buscando", to: "persona#buscando"
  post "persona/verificando", to: "persona#verificando"
  get "persona/buscar"
  get "persona/registrar"
  get "persona/:id/mostrar", to:  "persona#mostrar", as: "persona_mostrar"
  get "persona/:id/", to: "persona#editar", as: "persona_editar"
  patch "persona/:id" => "persona#actualizar", as: "persona_actualizar"
  put "persona/:id" => "persona#actualizar"
  delete "persona/:id" => "persona#eliminar", as: "persona_eliminar"


end

app/models/usuario.rb
class Usuario < ApplicationRecord
  self.table_name = 'Usuario'
  has_secure_password
end

app/controllers/usuario_controller.rb
class UsuarioController < ApplicationController
  before_action :set_usuario, only: [:mostrar, :editar, :actualizar, :eliminar] 
  
  def index
    @usuario = Usuario.all
  end

  def mostrar
  end

  def nuevo
    @usuario = Usuario.new
  end
  def editar
  end

  def crearUsuario
    @usuario = Usuario.new(usuario_params)
    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuario_url,
          notice: " ¡El usuario #{@usuario.nombre} fue creado satisfactoriamente! " }
      else
        #puts @usuario.password_digest 
        format.html { render :nuevo }
        #format.html { render @usuario_url }

      end
    end
  end
  def actualizar
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end
  def eliminar
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuario_path, notice: '¡el usuario fue eliminado satisfactoriamente!' }
      format.json { head :no_content }
    end
  end

  private
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    def usuario_params
       params.require(:usuario).permit(:nombre, :password,:correo, :fecha_registro, :estatus)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:persona_id, :nombre, :password_digest, :fecha_registro, :estatus)
    end
end

app/helpers/usuario_helper.rb
module UsuarioHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuario/_form.html.erb
<div class="row">
    <div class="col s12">
        <%=    form_with(model: usuario, url: usuario_path(usuario),:html => {:id => 'form_usuario' }, local: true) do |form| %>
                <% if usuario.errors.any? %>
                    <div id="error_explanation">
                        <h6><%= pluralize(usuario.errors.count, "error") %> No ha sido realizado el Registro de esta persona:</h6>

                        <ul>
                            <% usuario.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                        </ul>
                    </div>
                <% end %>

                <div class="row">
                    <div class="input-field col s4">
                        <%= form.label :nombre %>
                        <%= form.text_field :nombre %>
                    </div>

                    <div class="input-field col s4">
                        <%= form.label :correo %>
                        <%= form.text_field :correo %>
                    </div>
                </div>

                <div class="row">
                    <div class="input-field col s4">
                        <%= form.label :password  %>
                        <%= form.text_field :password %>
                    </div>


                    <div class="input-field col s4">
                        <%= form.label :password_confirmation, 'Confirmacion' %>
                        <%= form.text_field :password_confirmation%>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s4">
                        <%= form.check_box :estatus, id: "usuario_estatus", class: "filled-in" %>
                        <span>Estatus</span>
                        <!--  form.label :estatus, for: 'estatus' -->
                    </div>
                </div>
                <div class="actions">
                    <button class="btn waves-effect waves-light" type="submit" >Registrar
                        <i class="material-icons right">send</i>
                    </button>
                </div> 
<script>
var input = document.querySelector('form');
  var url =  String(input.action);
  if (url.match(/\./g)) {
      var nueva_url = url.replace(/http:\/\/localhost:3000/g,"");
      input.action= nueva_url.replace(/\./g,"/");
  }
</script>
            <% end %>
    </div>
</div>

app/views/usuario/editar.html.erb
<%= render 'form', usuario: @usuario %>

app/views/usuario/index.html.erb
<% if notice %>
    <script>
$(function() {
    M.toast({html:'<%= notice %>'}, 3000);
});
    </script>
<% end %>

<h1>Usuarios</h1>

 <%= link_to '<i class="material-icons"> add_circle_outline</i> '.html_safe, usuario_path  %>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Correo</th>
      <th>Fecha registro</th>
      <th>Estatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuario.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.correo %></td>
        <td><%= usuario.fecha_registro %></td>
        <td><%= usuario.estatus %></td>
        <td><%= link_to  '<i class="material-icons">remove_red_eye </i>'.html_safe, usuario_mostrar_path(usuario)  %> </td>
        <td><%= link_to '<i class="material-icons"> create </i>'.html_safe, usuario_editar_path(usuario) %></td>
        <td><%= link_to '<i class="material-icons"> delete </i>'.html_safe, usuario, method: :delete, data: { confirm: '¿ Estás seguro de querer eliminar el usuario?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo', usuario_path %>

app/views/usuario/nuevo.html.erb
<%= render 'form', usuario: @usuario %>

<%= link_to 'atras', usuario_url %>