config/routes.rb
Rails.application.routes.draw do
  #resources :organizacion
  get 'admin/index'
  get 'sesion/crear'
  get 'sesion/eliminarSesion' => 'sesion#eliminarSesion', as: "cerrarSesion"
  get 'sesion', to: 'sesion#inicio'
  post 'sesion', to: 'sesion#crear'
  #routes Acceso 
  get 'acceso', to: 'acceso#index'
  post 'acceso', to: 'acceso#verificacion'

  #routes usuario
  get 'usuario', to: 'usuario#index'
  get 'usuario/nuevo', to: 'usuario#nuevo'
  post 'usuario', to: 'usuario#crearUsuario'
  get 'usuario/:id' => 'usuario#editar', as: 'usuario_editar'
  get 'usuario/:id' => 'usuario#mostrar', as: 'usuario_mostrar'
  patch 'usuario/:id' => 'usuario#actualizar'
  put 'usuario/:id' => 'usuario#actualizar'

  delete "usuario/:id" => "usuario#eliminar", as: "usuario_eliminar"

  #routes verificacion
  get 'verificacion', to: 'verificacion#index'
  post 'verificacion', to: 'verificacion#buscando'
  get 'verificacion/credencial', to: 'verificacion#credencial'

 # resources :organizacion, :organizacion_path => { :update  => 'actualizar', :create => 'registrarOrganizacion'}
  #resources  :organizacions, controller: 'organizacion'
  #resolve("organizacions") { [:organizacion]  }
  #get 'organizacions', controlller: 'organizacion'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get  "organizacion" => "organizacion#index"
  get "organizacion/registrar" =>  "organizacion#registrar", as: :organizacion_nueva
  post "organizacion"  => "organizacion#registrarOrganizacion"
  patch "organizacion/:id/" => "organizacion#actualizar"
  put "organizacion/:id/" => "organizacion#update"
  get 'organzacion/:id' => 'organizacion#mostrar', as: :organizacion_mostrar
  get "organizacion/:id/", to: "organizacion#editar", as: :organizacion_editar

  delete "organizacion/:id" => "organizacion#eliminar", as: "organizacion_eliminar"
  #resources  :organizacion, only: [:update ]

  #This routes Persona controller and model
  get "persona", to: "persona#index"
  post "persona", to: "persona#registrarPersona"
  post "persona/buscando", to: "persona#buscando"
  post "persona/verificando", to: "persona#verificando"
  get "persona/buscar"
  get "persona/registrar"
  get "persona/:id/mostrar", to:  "persona#mostrar", as: "persona_mostrar"
  get "persona/:id/", to: "persona#editar", as: "persona_editar"
  patch "persona/:id" => "persona#actualizar", as: "persona_actualizar"
  put "persona/:id" => "persona#actualizar"
  delete "persona/:id" => "persona#eliminar", as: "persona_eliminar"


end

app/models/organizacion.rb
class Organizacion < ApplicationRecord
  self.table_name = 'Organizacion'
end

app/controllers/organizacion_controller.rb
class OrganizacionController < ApplicationController
  protect_from_forgery with: :exception
  before_action :autorizado
  before_action :set_organizacion, only: [:mostrar, :actualizar, :editar, :eliminar]

  def index
    @organizacion = Organizacion.all  
    @organizacion = Organizacion.order(:nombre).page(params[:page]).per_page(5)
  end

  def registrar
    @org = Organizacion.new
  end

  def editar
  end
  
  def mostrar
  end

  def show
  end


  def registrarOrganizacion
   @org = Organizacion.new(organizacion_params)
   respond_to do |format|
    if @org.save
      format.html { redirect_to @org, notice: '¡La organizacion fue creada exitosamente!.'  }
      format.json { render :mostrar, status: :created, location: @org  }
    else
      format.html { render :registrar  }
      format.json { render json: @org.errors, status: :unprocessable_entity  }
    end
   end
  end

  def actualizar
    respond_to do |format|
      if @org.update(organizacion_params)
        format.html { redirect_to organizacion_path , notice: 'Organizacion was successfully updated.' }
        format.json { render :mostrar, status: :ok, location: @org }
      else
        format.html { render :editar }
        format.json { render json: @org.errors, status: :unprocessable_entity }
      end
    end
  end

  def eliminar
    @org.destroy
    respond_to do |format|
      format.html { redirect_to organizacion_path, notice: '¡La organizacion fue eliminada satisfactoriamente!' }
      format.json { head :no_content }
    end
  end
  private

  def set_organizacion
    @org = Organizacion.find(params[:id])
  end

  def organizacion_params
    params.require(:organizacion).permit(:organizacion_id,:nombre)
  end


end

app/helpers/organizacion_helper.rb
module OrganizacionHelper
end

app/helpers/organizacions_helper.rb
module OrganizacionsHelper
end

app/views/organizacion/_form.html.erb
<h1>Organizacion#_form</h1>

<!--form_for (@org) do |f| -->
<%= form_with(model: org, url: organizacion_path(org), local: true)   do |f| %>
<% if @org.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@org.errors.count, "error" ) %> falló:</h2>
        <ul>
            <% @org.errors.full_messages.each do |message| %>
                <li> <%= message %></li>
            <%end%>
        </ul>
    </div>
<% end %>
<div class="field">
    <%= f.label :nombre%><br>
    <%= f.text_field :nombre%><br>
</div>
<div class="actions">
    <%= f.submit %>
</div>
<% end %>
<script>
  var input = document.querySelector('form');
  var url =  String(input.action);
  if (url.match(/\./g)) {
      var nueva_url = url.replace(/http:\/\/localhost:3000/g,"");
      //nueva_url = url.replace(/\./g,"/");
      input.action= nueva_url.replace(/\./g,"/");
  }
</script>

app/views/organizacion/editar.html.erb
<%= render 'form', org: @org %>

app/views/organizacion/index.html.erb
<% if notice %>
    <script>
$(function() {
    M.toast({html:'<%= notice %>'}, 3000);
});
    </script>
<% end %>

<h1>Listando Informacion </h1>

 <%= link_to '<i class="material-icons">note_add </i>'.html_safe, organizacion_nueva_path, class: "btn tooltipped" , 'data-position': "bottom", 'data-tooltip': "Registrar" %>
<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Fecha registro</th>
      <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
        <% @organizacion.each do |org| %>
          <tr>
            <td><%= org.nombre %></td>
            <td><%= org.fecha_registro %></td>
            <td><%= link_to '<i class="material-icons">remove_red_eye </i>'.html_safe, organizacion_mostrar_path(org) %></td>
            <td><%= link_to '<i class="material-icons">edit </i>'.html_safe, organizacion_editar_path(org) %></td>
             <td><%= link_to '<i class="material-icons">delete </i>'.html_safe, organizacion_eliminar_url(org), method: :delete, data: { confirm: 'Esta seguro de eliminar esta organizacion!?' } %></td>
          </tr>
        <%end%>
    </tbody>
</table>
<br>
  <%= will_paginate @organizacion %>

app/views/organizacion/mostrar.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organizacion:</strong>
  <%= @org.nombre %>
</p>


<p>
  <strong>Fecha Registro:</strong>
  <%= @org.fecha_registro %>
</p>
<p>
  <strong>Estatus:</strong>
  <%= @org.estatus %>
</p>

<%= link_to 'Editar', organizacion_editar_path(@org) %> |
<%= link_to 'Volver', organizacion_path %>

app/views/organizacion/registrar.html.erb
<h3>Nueva Organizacion</h3>
<%= render 'form', local:{url: organizacion_path}, org:@org %>