config/routes.rb
Rails.application.routes.draw do
  #resources :organizacion
  get 'admin/index'
  get 'sesion/crear'
  get 'sesion/eliminarSesion' => 'sesion#eliminarSesion', as: "cerrarSesion"
  get 'sesion', to: 'sesion#inicio'
  post 'sesion', to: 'sesion#crear'
  #routes Acceso 
  get 'acceso', to: 'acceso#index'
  post 'acceso', to: 'acceso#verificacion'

  #routes usuario
  get 'usuario', to: 'usuario#index'
  get 'usuario/nuevo', to: 'usuario#nuevo'
  post 'usuario', to: 'usuario#crearUsuario'
  get 'usuario/:id' => 'usuario#editar', as: 'usuario_editar'
  get 'usuario/:id' => 'usuario#mostrar', as: 'usuario_mostrar'
  patch 'usuario/:id' => 'usuario#actualizar'
  put 'usuario/:id' => 'usuario#actualizar'

  delete "usuario/:id" => "usuario#eliminar", as: "usuario_eliminar"

  #routes verificacion
  get 'verificacion', to: 'verificacion#index'
  post 'verificacion', to: 'verificacion#buscando'
  get 'verificacion/credencial', to: 'verificacion#credencial'

 # resources :organizacion, :organizacion_path => { :update  => 'actualizar', :create => 'registrarOrganizacion'}
  #resources  :organizacions, controller: 'organizacion'
  #resolve("organizacions") { [:organizacion]  }
  #get 'organizacions', controlller: 'organizacion'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get  "organizacion" => "organizacion#index"
  get "organizacion/registrar" =>  "organizacion#registrar", as: :organizacion_nueva
  post "organizacion"  => "organizacion#registrarOrganizacion"
  patch "organizacion/:id/" => "organizacion#actualizar"
  put "organizacion/:id/" => "organizacion#update"
  get 'organzacion/:id' => 'organizacion#mostrar', as: :organizacion_mostrar
  get "organizacion/:id/", to: "organizacion#editar", as: :organizacion_editar

  delete "organizacion/:id" => "organizacion#eliminar", as: "organizacion_eliminar"
  #resources  :organizacion, only: [:update ]

  #This routes Persona controller and model
  get "persona", to: "persona#index"
  post "persona", to: "persona#registrarPersona"
  post "persona/buscando", to: "persona#buscando"
  post "persona/verificando", to: "persona#verificando"
  get "persona/buscar"
  get "persona/registrar"
  get "persona/:id/mostrar", to:  "persona#mostrar", as: "persona_mostrar"
  get "persona/:id/", to: "persona#editar", as: "persona_editar"
  patch "persona/:id" => "persona#actualizar", as: "persona_actualizar"
  put "persona/:id" => "persona#actualizar"
  delete "persona/:id" => "persona#eliminar", as: "persona_eliminar"


end

app/models/persona.rb
class Persona < ApplicationRecord
  self.table_name = 'Persona'
  validates :nombre, :apellido, :cedula, :credencial, :organizacion_id,   presence: {message: "\t EL campo es requerido"}
  validates :cedula, :credencial, uniqueness: {message: "\t¡El dato ya existe!"}
  belongs_to :organizacion
  has_many :acceso


  def buscarPersona
    personas = Persona.all
    personas = personas.where([" nombre LIKE ?", "%#{nombre}%"]) if nombre.present?
    personas = personas.where([" apellido LIKE ?", "%#{apellido}%"]) if apellido.present?
    personas = personas.where([" cedula LIKE ?", cedula]) if cedula.present?
    personas = personas.where([" credencial LIKE ?", credencial]) if credencial.present?

    return personas
  end
  
  def buscarDatosPersonaCredencial( credencialPersona )
    
    datosPersona =  Persona.select(id, nombre, apellido, cedula).where("credencial = ? and estatus= ?",credencialPersona, true)

    if !datosPersona.empty?
      #puts "Existen datos asociados a esta credencial !"
      return datosPersona
    else
      puts "¡No existe información asociada a esta credencial #{credencial}! "
    end
  end
end

app/controllers/persona_controller.rb
class PersonaController < ApplicationController
  before_action :autorizado, :set_persona, only: [:mostrar, :editar, :actualizar, :eliminar] 
  #before_action :set_persona, only: [:mostrar, :editar, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.order(params[:sort]).page(params[:page]).per_page(5)
    #@personas = Persona.all
  end

  # GET /personas/1
  # GET /personas/1.json
  def mostrar
  end

  #GET /personas/busqueda

  def buscar
    @persona = Persona.new
  end

  def buscando
    @persona = Persona.new(persona_params)
  end

  # GET /personas/new
  def registrar
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def editar
  end

  # POST /personas
  # POST /personas.json
  def registrarPersona
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to persona_path, notice: ' ¡Persona ha sido creado satifactoriamente! ' }
        format.json { render :mostrar, status: :created, location: @persona }
      else
        format.html { render :registrar }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def actualizar
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def eliminar
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to persona_url, notice: '¡La persona fue eliminada satisfactoriamente!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:organizacion_id,:persona_id, :cedula, :nombre, :apellido, :credencial, :fecha_registro, :estatus)
    end
end

app/helpers/persona_helper.rb
module PersonaHelper
end

app/views/persona/_form.html.erb
<div class="row">
    <div class="col s12">
        <%= form_with model: persona,  url: persona_path(persona) , local: true do |f| %>
            <% if persona.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(persona.errors.count, "error") %> No ha sido realizado el Registro de esta persona:</h2>
                    <ul>
                        <% persona.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            <div class="row">
                <div class="input-field col s4">
                    <%= select("persona","organizacion_id", Organizacion.all.collect {|o| [ o.nombre, o.organizacion_id ]}, {prompt: 'Selecciona'})%>
                    <%= f.label :organizacion %>
                </div>
                <div class="input-field col s4">
                    <%= f.text_field :cedula, 'data-length': '10', id: "input_text" %>
                    <%= f.label :cedula, class:'active' %>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s4">
                    <%= f.text_field :nombre %>
                    <%= f.label :nombre %>
                </div>
                <div class="input-field col s4">
                    <%= f.text_field :apellido %>
                    <%= f.label :apellido %>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s4">
                    <%= f.text_field :credencial %>
                    <%= f.label :credencial %>
                </div>
                <div class="input-field col s4">
                    <%= f.check_box :estatus %>
                    <%= f.label :estatus %>
                </div>
            </div>
            <div class="actions">
                <button class="btn waves-effect waves-light" type="submit" >Registrar
                    <i class="material-icons right">send</i>
                </button>
            </div> 
        <% end %>
    </div>
</div>
<script>
var input = document.querySelector('form');
var url =  String(input.action);
  if (url.match(/\./g)) {
      var nueva_url = url.replace(/http:\/\/localhost:3000/g,"");
      input.action= nueva_url.replace(/\./g,"/");
  }
$(document).ready(function(){
     M.updateTextFields();
              
            
    $('.tooltipped').tooltip();
    $('select').formSelect();
              
});
</script>

app/views/persona/_validacionPersona.html.erb
<% if @persona.buscarPersona.empty? %>
    <p> No se encontró información </p>
<% else %>
     <h2>¡Saludos, que pase un feliz Día!</h2>
    <% @persona.buscarPersona.each do |c| %>
        <br>
        <div class="div">
        <p>Nombre: <%= c.nombre %></p>
        <p>apellido: <%= c.apellido %></p>
        <p>cedula: <%= c.cedula %></p>
        <p>fecha ingreso: <%= c.fecha_registro %></p>
    <%end%>
<%end%>

app/views/persona/buscando.html.erb
<h2>Resultados de Busqueda</h2>

<p><%= link_to 'Buscar', persona_buscar_url %></p>

<% if @persona.buscarPersona.empty? %>
    <p> No se encontró información </p>
<% else %>
    <% @persona.buscarPersona.each do |c| %>
        <br>
        <div class="div">
        <p>Nombre: <%= c.nombre %></p>
        <p>apellido: <%= c.apellido %></p>
        <p>cedula: <%= c.cedula %></p>
        <p>fecha ingreso: <%= c.cedula %></p>
    <%end%>
<%end%>

app/views/persona/buscar.html.erb
<h2> Busqueda avanzada </h2>
<%= form_for @persona, url: persona_buscando_url, :html => {:method => :post} do |form| %>

  <div class="field">
    <%= form.label :organizacion_id %>
    <%= form.text_field :organizacion_id %>
  </div>

  <div class="field">
    <%= form.label :cedula %>
    <%= form.text_field :cedula %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido %>
  </div>

  <div class="field">
    <%= form.label :credencial %>
    <%= form.text_field :credencial %>
  </div>


  <div class="field">
    <%= form.label :estatus %>
    <%= form.check_box :estatus %>
  </div>

  <div class="actions">
    <%= form.submit "buscar Persona" %>
  </div>
<% end %>

app/views/persona/editar.html.erb
<h1>Editing Persona</h1>

<%= render 'form',  persona: @persona %>

<%= link_to 'Mostrar', @persona %> |
<%= link_to 'Volver', persona_path %>

app/views/persona/index.html.erb
<% if notice %>
    <p> <%= notice %></p>
    <!--$(function(){M.toast( #{notice} , 2000 );});-->
    <script>
$(function() {
    M.toast({html:'<%= notice %>'}, 3000);
});
    </script>
<% end %>

<h1>Persona</h1>

<table>
  <thead>
    <tr>
        <th><%= link_to "Organizacion", :sort => "organizacion"%> </th>
        <th> <%= link_to "Cedula", :sort => "cedula" %></th>
        <th><%= link_to "Nombre", :sort => "nombre"%></th>
        <th><%= link_to "apellido", :sort => "apellido"%></th>
        <th><%= link_to "Credencial", :sort=> "credencial" %></th>
        <th><%= link_to "Fecha registro", :sort=> "fecha_registro" %></th>
        <th><%= link_to "estatus", :sort=> "estatus" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.organizacion.nombre %></td>
        <td><%= persona.cedula %></td>
        <td><%= persona.nombre %></td>
        <td><%= persona.apellido %></td>
        <td><%= persona.credencial %></td>
        <td><%= persona.fecha_registro %></td>
        <td><%= persona.estatus %></td>
        <td><%= link_to '<i class="material-icons">remove_red_eye </i>'.html_safe, persona_mostrar_url(persona) %></td>
        <td><%= link_to '<i class="material-icons"> create'.html_safe, persona_editar_url(persona) %></td>
        <td><%= link_to '<i class="material-icons"> delete'.html_safe, persona_eliminar_url(persona), method: :delete, data: { confirm: 'Esta seguro de eliminar esta persona!?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

  <%= will_paginate @personas %>
<br>

<%= link_to 'New Persona', persona_registrar_url %>

app/views/persona/mostrar.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Organizacion:</strong>
  <%= @persona.organizacion.nombre %>
</p>

<p>
  <strong>Cedula:</strong>
  <%= @persona.cedula %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @persona.apellido %>
</p>

<p>
  <strong>Credencial:</strong>
  <%= @persona.credencial %>
</p>

<p>
  <strong>Fecha registro:</strong>
  <%= @persona.fecha_registro %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @persona.estatus %>
</p>

<%= link_to 'Editar', persona_editar_path(@persona) %> |
<%= link_to 'Volver', persona_path %>

app/views/persona/new.html.erb
<%= render 'form', persona: @persona %>

<%= link_to 'Back', persona_url %>

app/views/persona/registrar.html.erb
<%= render 'form', persona: @persona %>

<%= link_to 'Back', persona_url %>